# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e84c72ab9d8bd5e7d5228f91d70a23d34d126fdb5bef0106b83c0b03ba362738d5ba9178a3a98fd18f00404df27c62ef864b7efdc4ae17ab20aef61e3835fefd

test:
  secret_key_base: ee07421aad62b2be7fcd6243962ad9c4f5cc32061d370cf51564b7067a4b35a8d5ad6a98cb66c318214befe40669f860d3477474ed16322f7e188983d619158b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
